### ISSUE TITLE
Joi stripUnknown does not work

### ISSUE THREAD

**Issue by PitchLabsAsh** [AndrewKeig/express-validation#116]
handleMutation within mutation.js seems to exclude the possibility of fields striped by Joi from being removed from the req.body.

**Comment by AndrewKeig** [comment]
Should work now.

**Comment by KonradLinkowski** [comment]
Still doesn't work for me. I don't
```
const querySchema = {
  query: Joi.object({
    label: Joi.string(),
    message: Joi.string().required(),
    labelColor: Joi.string().regex(colorRegex),
    color: Joi.string().regex(colorRegex),
    style: Joi.string().valid('plastic', 'flat', 'flat-square', 'for-the-badge', 'social')
  })
}

app.get('/badge', validate(querySchema, { context: true }, { stripUnknown: true }), (req, res) => {
  const svg = makeBadge(req.query)
  res.setHeader('Content-Type', 'image/svg+xml')
  res.send(svg)
})
```

I checked the code and I don't see any delete in the mutation.

**Comment by jimmy-insignia** [comment]
yeah It's also stilll doesn't work with me. I'm using stripUnknown: true. but I still saw ignored fields in req.body properties. please help @AndrewKeig

**Comment by ifeltsweet** [comment]
@AndrewKeig does not work for us too on v3.0.8.

**Comment by papandreou** [comment]
Fixed by #154
