### ISSUE TITLE
Validating array body 

### ISSUE THREAD

**Issue by kretz** [AndrewKeig/express-validation#36]
Hi,

Not sure if this is a bug or not, but let me explain what I want to do and the results I see.

I want to validate a that the body of a POST is a JSON array of objects. I have a schema like this:

```
{
  body: Joi.array().items(Joi.object()).required()
}
```

If I send in body data that is an array, `[{id:1}]` then I get this error:

```
Error: \"context\" must be an object\n
    at Object.internals.checkOptions (/Users/23046666/Projects/so-domain/node_modules/joi/lib/any.js:38:15)\n
    at [object Object].internals.Any.applyFunctionToChildren.internals.Any._validateWithOptions (/Users/23046666/Projects/so-domain/node_modules/joi/lib/any.js:628:19)\n
    at [object Object].root.validate (/Users/23046666/Projects/so-domain/node_modules/joi/lib/index.js:104:23)\n
    at validate (/Users/23046666/Projects/so-domain/node_modules/express-validation/lib/index.js:77:7)\n
    at /Users/23046666/Projects/so-domain/node_modules/express-validation/lib/index.js:42:24\n
    at Array.forEach (native)\n
    at /Users/23046666/Projects/so-domain/node_modules/express-validation/lib/index.js:39:55
```

It seems that Joi requires the body to be an objext. And to verify, If I send body data that is an object, {id:1}, then I don't see the error. (But instead the validation catches it, as it should.)

Looking at the code it seems that the body is set to the `context` attribute in options sent to Joi, and Joi checks that it is a Joi.object(). This was not the case in Joi 8.1.0, but has changed somewhere to Joi 8.4.2.

Do we really need to set the `context` attribute to the payload? Or is there any other way to keep it possible to validate arrays in the body?

Thanks!

**Comment by colthreepv** [comment]
Okay, nice catch first of all! 😉 

The problem is the [context sent to Joi](https://github.com/AndrewKeig/express-validation/blob/master/lib/index.js#L41-L42)

The original idea was pass the request as a context so developers could reference other keys without referencing `body/query/etc` #17 

A quick fix for your problem would be to set `contextRequest: true` in the global or in the specific options.


I am going to review this `context` part.
I think it's useless to pass a context if you're referring to the same request section ('body' keys referencing to other 'body' keys)

It's necessary when referencing to other request section, ex: `request.body.id` that requires to be the same as `request.query.id`

So I think I can end up passing the Entire request as context, always, and it should fix both behaviours

**Comment by matt-blanchette** [comment]
+1

**Comment by colthreepv** [comment]
This has been addressed in the upcoming 2.x release, writing changelog as we speak

**Comment by colthreepv** [comment]
Should be fixed, a test would be bliss in this case, can you please test it if you have time?

**Comment by mytharcher** [comment]
I am using v1.0.2 and still can't use array for body. Any updates?

**Comment by nthgol** [comment]
+1 and it doesn't work I have the exact same use case as https://github.com/hapijs/joi/issues/1437#issue-297588870

**Comment by KErez** [comment]
Is this one solved? I still get this error.
I'm using Joi@14.3.1 and express-validation@1.0.2

**Comment by btav** [comment]
Here is a quick example of how to fix this issue by setting `contextRequest` to `true`. 

```
const Joi = require('joi');

const exampleSchema = Joi.array()
  .items(
    Joi.object().keys({
      example: Joi.number().required(),
    })
  )
  .required();

module.exports = {
  example: {
    body: exampleSchema,
    options: {
      contextRequest: true,
    },
  },
}
```

**Comment by ulalawell** [comment]
+1
